# Generated by Django 2.0.1 on 2018-06-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ans',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='ans_text',
            new_name='answer_text',
        ),
    ]
