# Generated by Django 2.0.1 on 2018-06-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180616_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Ans',
        ),
        migrations.RenameField(
            model_name='ans',
            old_name='answer_text',
            new_name='ans_text',
        ),
    ]
